/**
 * Node-layer (Vitest) — click-to-move through the shop floor's merchant row (a co-op report of the walk bumping a merchant).
 *
 * The owner identified the room: the shop floor (`ShopStart`), generated by
 * `KinkyDungeonCreateShopStart` (`Game/src/map/KinkyDungeonAlt.ts`) and reached in the stock game the
 * same way `Game/src/prison/KinkyDungeonJail.ts:2261` reaches it
 * (`KinkyDungeonCreateMap(KinkyDungeonMapParams.shoppe, "ShopStart", ...)`). Its quest-giver row —
 * `BlacksmithQuest`, `ArmorerQuest`, `BowyerQuest`, `AntiqueQuest` (`Game/src/enemy/KinkyDungeonEnemiesList.ts`)
 * — is what the screenshot shows standing on the display pedestals with speech bubbles. NONE of them
 * carry `immobile: true` (unlike the prison/doll captives `mp-fastmove-immobile-npc.spec.ts` covers),
 * so `KinkyDungeonFindPath` only WEIGHT-penalises their tiles (`KDAutoPathEnemyWeight = 6`,
 * `KinkyDungeonPathfinding.ts:271-287`) rather than excluding them outright.
 *
 * This is the cheapest honest repro, built with the SAME production map-gen call the stock game uses
 * — no synthetic room, no hand-placed entities. It proves the walk-through-the-row behaviour is
 * **stock KD pathfinding**, present with ZERO co-op code involved (test one, below): standing on the
 * open floor in front of the stalls and clicking past them, the cost of detouring around four
 * weighted tiles loses to the cost of a longer path around, so `KDFastMoveTo` routes straight through
 * all four. Test two proves co-op does not make this WORSE or DIFFERENT: the identical click, replayed
 * after the exact render-state round trip the thin client performs, produces the identical route.
 *
 * Imports the harness under tools/mp-server/** only; `KinkyDungeonCreateMap` is a Game/src production
 * function invoked exactly as the stock game invokes it — not a reimplementation.
 */
import { describe, it, expect } from 'vitest';
/* eslint-disable @typescript-eslint/no-var-requires */
const { HeadlessHost } = require('../../tools/mp-server/headless-host');

const BOOT_TIMEOUT = 180_000;

/** The four quest-giver tiles the shop floor's merchant row occupies (see header). */
const MERCHANT_ROW = [
	{ x: 3, y: 5, name: 'BlacksmithQuest' },
	{ x: 4, y: 5, name: 'ArmorerQuest' },
	{ x: 5, y: 5, name: 'BowyerQuest' },
	{ x: 6, y: 5, name: 'AntiqueQuest' },
];

/** Generate the REAL shop floor with KD's own production call (`KinkyDungeonJail.ts:2261`). */
function buildShopFloor(host: any) {
	return host.eval(`(function(){
		KinkyDungeonCreateMap(KinkyDungeonMapParams.shoppe, "ShopStart", "", MiniGameKinkyDungeonLevel,
			undefined, undefined, undefined, {x: 0, y: 0}, false, undefined);
		return { start: KDMapData.StartPosition, entities: KDMapData.Entities.length };
	})()`);
}

/** Run KD's own click-to-move (stock `KDFastMoveTo`, unmodified) and return the queued path. */
function fastMoveRoute(host: any, px: number, py: number, tx: number, ty: number) {
	return host.eval(`(function(){
		KinkyDungeonPlayerEntity.x = ${px | 0}; KinkyDungeonPlayerEntity.y = ${py | 0};
		// Headless-safe vision pass — see mp-fastmove-immobile-npc.spec.ts for why this is needed
		// and why it is safe (KDUpdateVision's PIXI draw block is gated on CamX !== undefined).
		KDUpdateDoorNavMap();
		KDUpdateVision();
		KinkyDungeonFastMovePath = [];
		KDFastMoveTo(${tx | 0}, ${ty | 0});
		var path = KinkyDungeonFastMovePath ? KinkyDungeonFastMovePath.slice() : [];
		KinkyDungeonFastMovePath = [];
		return path;
	})()`);
}

function crossesMerchantRow(path: any[]) {
	return path.some((pt) => MERCHANT_ROW.some((m) => m.x === pt.x && m.y === pt.y));
}

describe('KDFastMoveTo on the real shop floor, walking the open row in front of the merchants', () => {
	it('STOCK single-player: the route cuts straight through the merchant row — not a co-op bug', () => {
		const h = new HeadlessHost({ id: 'shop-ground-truth' });
		h.boot();
		h.init({ seed: 'kdm315-shop-a' });
		const floor = buildShopFloor(h);
		expect(floor.entities, 'the shop floor must have spawned its NPCs').toBeGreaterThan(0);

		// Standing on the open floor directly in front of the stalls (row 6, one tile below the
		// merchant row at row 5) and clicking to the open pedestal just past the last merchant.
		const path = fastMoveRoute(h, 2, 6, 7, 5);
		expect(path.length, 'KD must find a route at all').toBeGreaterThan(0);
		// This IS the reported bug, reproduced with zero co-op code: KD's own weight-only
		// (non-immobile) blocking lets a long enough detour lose to a short straight line through
		// four weighted tiles. Recorded as evidence for the owner, not asserted as a requirement —
		// a fix that makes this false is exactly what would change the stock route this spec pins.
		expect(crossesMerchantRow(path), 'reproduction: stock KD walks through the merchant row here')
			.toBe(true);
	}, BOOT_TIMEOUT);

	it('co-op (post render-state round trip): the identical click produces the identical route', () => {
		const server = new HeadlessHost({ id: 'shop-server' });
		server.boot();
		server.init({ seed: 'kdm315-shop-a' });
		buildShopFloor(server);
		server.eval(`(function(){ KinkyDungeonPlayerEntity.x = 2; KinkyDungeonPlayerEntity.y = 6; })()`);

		const snap = server.serializeRenderState();
		snap.bundle = server.capturePlayer();

		// A SEPARATE instance stands in for the browser, exactly as in mp-fastmove-immobile-npc.spec.ts.
		const client = new HeadlessHost({ id: 'shop-client' });
		client.boot();
		client.init({ seed: 'unrelated-seed-for-the-client' });
		const applied = client.applyRenderState(snap);
		expect(applied.ok).toBe(true);

		const path = fastMoveRoute(client, 2, 6, 7, 5);
		expect(path.length, 'the client must still find a route at all').toBeGreaterThan(0);
		// PARITY, not a new assertion: co-op reproduces the exact same stock behaviour, no worse and
		// no different. If this ever disagrees with the single-player spec above, that disagreement —
		// not "crosses" by itself — is the co-op-specific bug.
		expect(crossesMerchantRow(path), 'co-op must match single player, not diverge from it').toBe(true);
	}, BOOT_TIMEOUT);
});
